const {babelfish} = require("./cli.js")
babelfish("./models/samples/1.wav", false)
babelfish("./models/samples/2.wav", false)
babelfish("./models/samples/3.wav", false)
babelfish("./models/samples/4.wav", false)
babelfish("./models/samples/5.wav", false)
babelfish("./models/samples/6.wav", false)
babelfish("./models/samples/7.wav", false)
babelfish("./models/samples/8.wav", false)
