const {babelfish} = require("./cli.js")
babelfish("./samples/1.wav", false)
babelfish("./samples/2.wav", false)
babelfish("./samples/3.wav", false)
babelfish("./samples/4.wav", false)
babelfish("./samples/5.wav", false)
babelfish("./samples/6.wav", false)
babelfish("./samples/7.wav", false)
babelfish("./samples/8.wav", false)
